### ISSUE TITLE
is this maintained?

### ISSUE THREAD

**Issue by AVVS** [sematext/spm-agent-nodejs#14]
seems like there are no updates for a while - are you guys planning to maintain node.js integrations?

**Comment by otisg** [comment]
Yes, this is maintained.  Did you find a bug or have some suggestions or contributions you'd like to make?

**Comment by AVVS** [comment]
https://www.npmjs.com/package/measured <https://www.npmjs.com/package/measured>

this is widely used and has not been updated in 3 years, because it was split up into multiple versions with various improvements
that would be a good starting point

next one is node 10, where gc-stats is not really up to date - so cant get that either

so small things like that :)

**Comment by megastef** [comment]
@AVVS Please check release 2.0.x - node measured was updated, and gc-stats module, working on node v6, v8, v10, v11. 
We had to drop support for Node v4. Please note It is not always easy to be up-to-date and backward compatible with older node versions. Feel free to open issues or pull requests or improvements.
