### ISSUE TITLE
Move from measured to measured-core

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent-nodejs#15]
$ npm i -g spm-agent-nodejs

[output]
npm WARN deprecated measured@1.1.0: This package has been renamed to measured-core, all versions of measured have been re-released under measured-core, please update your package and consider updating to the newest version. See https://github.com/yaorg/node-measured for latest updates.

**Comment by megastef** [comment]
This was done a long time ago: https://github.com/sematext/spm-agent-nodejs/commit/b81dc7a5f3944e9f7aadb602ca0ca715a2b98fdd#diff-7920d0ba3676b8c6c025982c20863c71

I could not reproduce the issue. Maybe one of the sub-modules was not updated to measured-core.
