### ISSUE TITLE
Add support to monitor Worker Threads in Node 12

### ISSUE THREAD

**Issue by megastef** [sematext/spm-agent-nodejs#16]
Currently, the agent counts workers forked by cluster-module. It might be useful to count workerThreads as well. 

See:
https://nodejs.org/dist/latest-v12.x/docs/api/worker_threads.html#worker_threads_worker_threadid

**Comment by adnanrahic** [comment]
This was implemented as part of the Process Monitoring features, added in v3.0.0. We can resolve this issue.
