### ISSUE TITLE
Monitoring Node.js app and AWS OpsWorks

### ISSUE THREAD

**Issue by otisg** [sematext/spm-agent-nodejs#5]
This is a request from one of the SPM users:

> Is there a way to use the monitor with just file configuration?
> The issue is that I use AWS OpsWorks to deploy and the only way of configuring that is by have the config previously in a file or in an environment variable.

**Comment by megastef** [comment]
Yes. All configuration options could be set via ENV vars. E.g. 
```
export SPM_TOKEN=token
# default is SaaS at sematext.com, URL needs to be changed for on-prem to the local SPM receiver
export SPM_RECEIVER_URL=https://local-spm-server:8084/_bulk
export EVENTS_RECEIVER_URL=https://local-event-receiver/
export SPM_DB_DIR=/tmp
export SPM_LOG_DIRECTORY=./logs
export SPM_LOG_LEVEL=error
export SPM_LOG_TO_CONSOLE=true
export HTTPS_PROXY=http://my-local-proxy-server
```
