### ISSUE TITLE
Update/remove vulnerable packages from npm

### ISSUE THREAD

**Issue by Kaladin13** [sematext/spm-agent-nodejs#52]
`morgan-json` is a [well-known](https://security.snyk.io/vuln/SNYK-JS-MORGANJSON-2976193) vulnerable package, and this agent uses it. I suggest removing it and replacing with custom `winston` transport, as right now, this vuln makes this soft unusable in production

**Comment by Kaladin13** [comment]
![image](https://user-images.githubusercontent.com/80884234/203403834-3dd4729b-1806-41f5-a54a-6fc114cb0c49.png)
Current package state

**Comment by regiluze** [comment]
All critical vulnerabilities removed.
