### ISSUE TITLE
PM2 Cannot find module

### ISSUE THREAD

**Issue by wespen** [sematext/spm-agent-nodejs#8]
Starting PM2 JSON with "node_args":"-r 'spm-agent-nodejs'",
results in an error
PM2        | Error: Cannot find module 'spm-agent-nodejs'
PM2        |     at Function.Module._resolveFilename (module.js:440:15)
PM2        |     at Function.Module._load (module.js:388:25)
PM2        |     at Module.require (module.js:468:17)
PM2        |     at module.js:631:12
PM2        |     at Array.forEach (native)
PM2        |     at Function.Module._preloadModules (module.js:630:12)
PM2        |     at preloadModules (bootstrap_node.js:323:38)
PM2        |     at startup (bootstrap_node.js:143:9)
PM2        |     at bootstrap_node.js:467:3

Tried with ./spm-agent-nodejs and ./node_modules/spm-agent-nodejs
and installing spm-agent-nodejs with -g flag.

Adding var spmAgent = require ('spm-agent-nodejs'); in js doesn't produce the error, however some of the charts are empty (CPU, workers, memory)

node v6.3.1, PM2 v2.0.15

**Comment by megastef** [comment]
Have you tried to use "node -r absolutePath/node_modules/spm-agent-nodejs" ? 
And I think all settings needs to be done in the PM2 config: 
https://github.com/sematext/spm-agent-nodejs/wiki#how-to-configure-spm-agent-nodejs-for-my-app-using-pm2-process-manager

**Comment by wespen** [comment]
added absolute path. Doesnt crash now, but I dont see any data in charts on dashboard.

**Comment by megastef** [comment]
And the config? https://github.com/sematext/spm-agent-nodejs/wiki#how-to-configure-spm-agent-nodejs-for-my-app-using-pm2-process-manager

Any error logs? in ./spmlogs dir?

**Comment by megastef** [comment]
Have you create the app of type "Node.js" in SPM? Feel free to drop me a mail e.g with appID to stefan.thies@sematext.com (just to check server side).

**Comment by megastef** [comment]
@wespen any news? Can we close the issue?

**Comment by wespen** [comment]
Close.
Full path works
